### ISSUE TITLE
Error updating from local files: Unexpected character '52' found when expecting key.

### ISSUE THREAD

**Issue by ajhix36** [Theo47/depressurizer#64] opened 2016-09-10 14:37 UTC

**Comment by ajhix36** [comment] 2016-09-10 14:38
Just upgraded to 7.1.3 and this is happening.

**Comment by Theo47** [comment] 2016-09-10 15:22
So this only happens on version 7.1.3 and not on 7.1.2?

Can you upload your Steam\appcache\appinfo.vdf file?

**Comment by ajhix36** [comment] 2016-09-10 15:44
No this apparently happens on all versions back to 6.3.0. Just tried them one by one.

**Comment by ajhix36** [comment] 2016-09-10 15:46
https://ufile.io/41d46

**Comment by ajhix36** [comment] 2016-09-10 15:47
I tried on my other computer now its saying '64' is the unexpected character.

**Comment by Theo47** [comment] 2016-09-10 16:34
My bad. Apparently what i need is Steam\appcache\packageinfo.vdf

Can you upload that?

**Comment by ajhix36** [comment] 2016-09-10 16:35
https://ufile.io/b7135

**Comment by Theo47** [comment] 2016-09-10 16:36
That was quick.

**Comment by ajhix36** [comment] 2016-09-10 19:38
Any luck?

**Comment by Theo47** [comment] 2016-09-10 22:03
Well your packageinfo.vdf file allowed me to reproduce the problem.

The problem is that it is reading something from packageinfo.vdf that it didn't expect.

Sadly packageinfo.vdf is a mess so i have no idea what we were expecting to read from there in the first place. I'll have to take a closer look on the code in order to figure that out.

**Comment by DarkDerry** [comment] 2016-09-23 13:33
Same problem here--I've never had a problem with this before, until 0.7.1.3.  I also tried to go back several versions and the problem is in those versions now too (they weren't before and worked fine).

My says "Unexpected character '10' found when expecting key."  Originally, I was getting "Unexpected character '48' found when expecting key.", but I saw this post, deleted my vdf files and redownloaded them, then it changed from '48' to '10'.

**Comment by ibigfire** [comment] 2016-09-28 01:04
My unexpected character is 57, if that helps.  Would you like my packageinfo.vdf as well?

**Comment by kazerniel** [comment] 2016-10-18 11:21
I have this error too nowadays whenever I open Depressurizer. My number is '51'. Also the most recent game in my Library (G Prime) doesn't show up in Depressurizer even after updating the game list. Maybe it's related?

**Comment by bloodythorn** [comment] 2016-10-29 22:27
Same issue, cept character '45'. 

``
Error updating from local files:

Unexpected character '45' found when expecting key.
``


[appinfo.vdf.txt](https://github.com/Theo47/depressurizer/files/560185/appinfo.vdf.txt)

**Comment by Zhuinden** [comment] 2016-10-30 08:23
They've probably changed the file format, and reading through the VDF came from the original "rallion" version.

I wonder if there is another data source for this data...

**Comment by Zhuinden** [comment] 2016-10-30 09:29
There is a file here named `C:/Program Files (x86)/Steam/userdata/74694030/7/remote/sharedconfig.vdf` which seems to contain what category each game is put into, but it doesn't seem to show games that do not have any categories -_-

**Comment by Theo47** [comment] 2016-10-30 14:09
Yeah, it seems that Steam changed its format for packageinfo.vdf which is what is causing the problem. What number you get isn't important. It is just the hex code of the first character it didn't expect to read.

Depressurizer was supposed to fall back to updating the gamelist from the web if local update failed but it seems that didn't work properly either.

For now, i disabled local update till i can get packageinfo.vdf parsing working again and fixed the web update.

So can someone try this version and tell me if it works correctly? Mainly if all games appear properly now.

https://dl.dropboxusercontent.com/u/46188332/depressurizer.zip

**Comment by Copypasty** [comment] 2016-10-30 17:30
Yup, no error pops up and everything else seems to be working as intended when I run that. (I too was having the character error pop up)

**Comment by Zhuinden** [comment] 2016-10-30 18:01
@Theo47 yes, it works!

**Comment by n0x11** [comment] 2016-11-07 19:05
No error popups for me with the new version from the dropbox link.
Only half my games are shown in depressurizer though.

**Comment by Zhuinden** [comment] 2016-11-07 19:39
@n0x11 is your profile public or private? You might need a public profile for web sync.

**Comment by Theo47** [comment] 2016-11-07 20:09
@n0x11 When you launch depressurizer, at bottom it should say something like "Updated X DB entries from AppInfo". Can you tell me what X is?

Also can you go to Profile->Edit Profile Info->Ignored Games and check "Don't ignore unknown apps"? Restart depressurizer after that (saving changes) and see if it recognizes more games.

**Comment by n0x11** [comment] 2016-11-07 20:27
Oh sorry guys, @Zhuinden was right..
I must have changed it in the past..

Thank you and keep up the amazing work!!

**Comment by Theo47** [comment] 2016-11-07 20:33
In that case i am closing this. New version should be (officially) out in a few mins.

**Closed by Theo47** 2016-11-07 20:33 UTC
