### ISSUE TITLE
No game data found. Please make sure the custom URL is spelled correctly. 

### ISSUE THREAD

**Issue by ryanneve** [Theo47/depressurizer#80] opened 2016-11-25 21:50 UTC
Since upgrading to latest version I get: No game data found. Please make sure the custom URL is spelled correctly. I tried deleting profile, and downloading new copy, but can't get it working.

**Comment by ryanneve** [comment] 2016-11-25 22:10
I tried putting in custom url as:
steamcommunity.com/id/NXXXXXXXXXN
but got "Could not find the Steam profile specified. When I put same URL in incognito browser I can see my profile.

**Comment by mkava** [comment] 2016-12-25 11:30
I am running version 0.7.1.4 according the About dialog (latest Nov 7th release), just updated from v0.6.1.0.

I can confirm that this error is still an issue and best I can tell, it is related not to the custom URL but instead caused by the "Prefer XML" functionality. In the Edit Profile dialog, I have selected by account from the list, nothing manually entered in the custom URL option so that should not be poisoning the data any, and the "Prefer XML" is selected in the Settings dialog.

I was experiencing the same dialog prompt when using Profile > Update Game List, so I looked at the logfile to see if there was some exception getting eaten and not presented in the UI or if I could see how/where the web request was being executed for the poll. The web request URLs I was seeing are available below. The XML version would always error, regardless of the profile being public or private (confirmed public in profile settings and incognito session). I believe the fix for this issue is to actually fallback to the HTML scrape if the XML scrape is not working, as would be expected with "Prefer" functionality.

Thanks for continuing this awesome tool! :+1: 

```
"Prefer XML": http://steamcommunity.com/profiles/<STEAMID>/games?tab=all&xml=1
"Only HTML": http://steamcommunity.com/profiles/<STEAMID>/games?tab=all
```

Results on every XML scrape attempt:
```
<gamesList>
<steamID64>STEAMID</steamID64>
<steamID>
<![CDATA[ USERNAME ]]>
</steamID>
<error>
<![CDATA[ This profile is private. ]]>
</error>
</gamesList>
```

**Comment by Theo47** [comment] 2017-03-10 01:15
@ryanneve It only wanted the NXXXXXXXXXN part of  steamcommunity.com/id/NXXXXXXXXXN. If you used the full url then that was why you were getting an error.

**Comment by Theo47** [comment] 2017-03-10 01:42
@mkava After testing it, it seems that upon switching your profile from private to public (and vice versa) the html page updates instantly but the xml version can take up to a couple of hours before it gets updated to reflect the change. 

The "prefer xml" option did fallback to html under most cases. This case was an exception since it assumed that if xml says your profile is private then html would say the same.

Now it should fallback to HTML under that case too. 520d8dd6f8461e7bc6ea33bd20c473cf08a959bb

**Closed by Theo47** 2017-03-10 01:42 UTC
Labels: bug
