### ISSUE TITLE
Error saving database

### ISSUE THREAD

**Issue by Darkcloud1987** [Theo47/depressurizer#55] opened 2016-05-23 22:23 UTC
When I open Depressurizer or try to save the database I always get "Error saving database" 
![dkljahc](https://cloud.githubusercontent.com/assets/3299458/15486375/7346edaa-2145-11e6-906d-8d9f0eb5ba44.png)

it basically translates to hexadecimal value 0x01 is an invalid character.

This results in an unfinished Database that ends in the middle of a new entry.

**Comment by Theo47** [comment] 2016-05-24 16:33
You said it stopped in the middle of a new entry. What entry is that, and at what part of the entry did it stop at? Does it always stop at that specific entry?

Also try using this database and launching the program to see if you still get that error.
[GameDB.xml.gz](https://github.com/Theo47/depressurizer/files/279966/GameDB.xml.gz)

If you don't get an error then try updating the database and then saving it to see if you get an error in that case.

**Comment by Darkcloud1987** [comment] 2016-05-24 19:39
Its always around the same point. 

>   <game>
    <id>324250</id>
    <name>Knights of Pen and Paper - Haunted Fall</name>
    <lastAppInfoUpdate>1464118607</lastAppInfoUpdate>
    <type>DLC</type>
    <platforms>Windows, Mac, Linux</platforms>
    <parent>231740</parent>
    <hltbMain>344</hltbMain>
    <hltbExtras>494</hltbExtras>
    <hltbCompletionist>752</hltbCompletionist>
  </game>
  <game>
    <id>324270</

Sometimes it stops before the 324270 and doesn't finish knights of pen and paper. 

with your database the error also occurs but stops at a different entry:

> <id>325503</id> <name>RPG Maker: Inspirational Vol. 3</name> <lastStoreUpdate>1464096665</lastStoreUpdate> <lastAppInfoUpda

**Comment by Darkcloud1987** [comment] 2016-05-24 19:39
>     <id>325503</id>
    <name>RPG Maker: Inspirational Vol. 3</name>
    <lastStoreUpdate>1464096665</lastStoreUpdate>
    <lastAppInfoUpda

**Comment by Theo47** [comment] 2016-05-25 01:24
Well since i can't reproduce this, i am going to need more information from you.

Try using this exe. It should give a more detailed message about where the error occurs.
[Depressurizer.zip](https://github.com/Theo47/depressurizer/files/280799/Depressurizer.zip)

Firstly delete the database and launch depressurizer again. Tell me if you get this error the first time you launch depressurizer after you deleted the database.
After that use the database i uploaded above and launch depressurizer again. Repeat that 2 more times, each time replacing the database with a fresh copy of the database above.
Tell me if the error occured on the same place or different ones as well as where that was.

Also upload your appinfo.vdf file. It should be located on either "C:\Program Files (x86)\Steam\appcache\appinfo,vdf" or "C:\Program Files\Steam\appcache\appinfo,vdf"

**Comment by Theo47** [comment] 2016-05-25 11:15
Oh right, 1 more thing. Do this first.
Go to Tools->Settings and disable "Update DB with AppInfo on program start".
Then use the database above and relaunch Depressurizer.
If you don't get an error this time then uploading you appinfo.vdf file will be enough.

**Comment by Darkcloud1987** [comment] 2016-05-27 11:54
Really strange with that database and after starting the exe from above with the database included it seems to work with both the exe from the zip and the one I already have localy. I imported the steam database again and saved the database again and nor error but here is the appinfo.vdf anyways: 
[appinfo.zip](https://github.com/Theo47/depressurizer/files/286393/appinfo.zip)

**Comment by Theo47** [comment] 2016-05-27 13:08
Strange. The database included with the exe was the same as the database i attached earlier on. I just included it with the exe too for convenience. So i can't think of any reason it would get suddenly fixed.
But well since it got fixed, i am closing this issue. Without additional info, i wouldn't be able to figure out the cause of the error anyway.

**Closed by Theo47** 2016-05-27 13:08 UTC
