### ISSUE TITLE
Broken ui

### ISSUE THREAD

**Issue by LennyPenny** [Theo47/depressurizer#110] opened 2017-06-25 19:58 UTC
![pew](https://vgy.me/cS2x8k.png)

Windows 10 creators update

**Comment by mvegter** [comment] 2017-06-30 18:02
@LennyPenny I do not have this problem, could you upload or paste your Windows information here? You can find this in Settings -> System -> About.

My pc:
![system info](https://user-images.githubusercontent.com/25134477/27748254-01f7ebaa-5dcf-11e7-890d-5583823c879e.png)

**Comment by mvegter** [comment] 2017-07-22 15:27
@LennyPenny Closing this as a duplicate of #12

**Closed by mvegter** 2017-07-22 15:27 UTC
Labels: bug
