### ISSUE TITLE
Error updating from local files: Unexpected character '56' found when expecting key.

### ISSUE THREAD

**Issue by wellkens** [Theo47/depressurizer#69] opened 2016-09-30 17:52 UTC
First
![2016-10-01_013255](https://cloud.githubusercontent.com/assets/22547715/19000796/14aebc8a-8777-11e6-9cab-35d1a9e28f4a.jpg)

Then
![2016-09-29_004605](https://cloud.githubusercontent.com/assets/22547715/19000789/08a81774-8777-11e6-950d-306336c66ac4.jpg)

Several days ago, I reinstalled WIN10 x64 and downloaded Depressurizer 0.6.1.0, rallion released it on 18 Dec 2014. In the first run, it was OK. But when I ran on the next day (the second run), there was something wrong as shown in the second image above, the same to my other computer(WIN7 x64). 

After deleting 0.6.1.0 and installing 0.7.1.3, showed in the two images above

**Comment by RushNY** [comment] 2016-10-09 16:26
Having a similar issue with mine being "37" instead.  Everything in localconfig.vdf looks in order, I found the only instance of 37 in it and it follows the format the rest of the licenses do.

**Comment by wellkens** [comment] 2016-10-09 17:07
I think the problem is related to the steam update. After updating Depressurizer, the problem will be  solved perhaps

**Comment by lhriley** [comment] 2016-10-15 02:47
This error occurs on launch, as well as when selecting `Profile > Update Game List CTRL+U` from the main window. Note that the value of the "Unexpected character" is likely relative to the number of games in your library (assumption).

Log:
```
ERR: Exception when performing local update.
Depressurizer.ParseException: Unexpected character '182' found when expecting key.
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.PackageInfo.LoadPackages(String path)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
   at Depressurizer.FormMain.UpdateLibrary()
```

**Comment by lhriley** [comment] 2016-10-15 07:34
Noticed this is a duplicate of #64

**Comment by Zhuinden** [comment] 2016-10-31 07:34
Fixed in https://github.com/Theo47/depressurizer/issues/64#issuecomment-257153102

**Closed** 2017-03-08 12:51 UTC
